<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function ajman_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {


  // Check if the form ID is node_services_form.
  if ($form_id == 'node_services_form') {
    // Array of field names to wrap.
    $fields_to_wrap = ['field_internal_assessor_name', 'field_internal_assessor_position'];

    // Iterate through each field to add a wrapper and custom class.
    foreach ($fields_to_wrap as $field_name) {
      if (isset($form[$field_name])) {
        // Add a custom class to the form element wrapper.
        $form[$field_name]['#attributes']['class'][] = 'col';
      }
    }

    // dpm($form['field_service']['widget'][0]['subform']);

        // Add a wrapper ID to the 'field_elloborate' field for jQuery targeting.
        $form['field_service']['widget'][0]['subform']['field_elloborate']['#prefix'] = '<div id="field-elloborate-wrapper">';
        $form['field_service']['widget'][0]['subform']['field_elloborate']['#suffix'] = '</div>';
    
        // Attach the custom JavaScript file.
        $form['#attached']['library'][] = 'ajman_core/ajman_core_js';

            // Add custom validation handler.
      $form['#validate'][] = 'ajman_core_validate_minimum_services';

  }


  // Check if the form ID is node_services_form.
  if ($form_id == 'node_evaluation_form') {
    // Array of field names to wrap.
    $fields_to_wrap = ['field_meeting_day', 'field_date', 'field_support_services_committee', 'field_support_decision', 'field_media_decision', 'field_media_committee_br_observa', 'field_service_evaluation_committ', 'field_evaluation_decision', 'field_technical_committee_br_obs', 'field_tech_cmte_decision'];

    // Iterate through each field to add a wrapper and custom class.
    foreach ($fields_to_wrap as $field_name) {
      if (isset($form[$field_name])) {
        // Add a custom class to the form element wrapper.
        $form[$field_name]['#attributes']['class'][] = 'col';
      }
    }
    
    // Change the save button text to "Submit".
    if (isset($form['actions']['submit'])) {
      $form['actions']['submit']['#value'] = t('Submit');
    }

  }


  
}



/**
 * Custom validation handler to ensure at least two services are submitted.
 */
function ajman_core_validate_minimum_services(array &$form, FormStateInterface $form_state) {
  // Initialize a counter for services.
  $num_services = 0;

  // Get all the form values.
  $values = $form_state->getValues();

  // Loop through the submitted values to count the services.
  foreach ($values['field_service'] as $key => $service) {
    // Check if this is a valid service item (not empty).
    if (!empty($service['value'])) {
      $num_services++;
    }
  }

  // Check if there are at least 2 services.
  if ($num_services < 2) {
    $form_state->setErrorByName('field_service', t('You must submit at least two services.'));
  }
}

